### ISSUE TITLE
Source of radiative efficiencies

### ISSUE THREAD

**Issue by cardosan** [gschivley/ghgforcing#5]
Hey Greg,
could not understand from were exactly you took or how were calculated the [radiative efficiencies](https://github.com/gschivley/ghgforcing/blob/master/ghgforcing/ghgforcing.py#L11).
Would you be so kind to document it?

**Comment by gschivley** [comment]
They are from the Supplementary Material to Chapter 8 of the 5th Assessment Report. I'm having trouble finding a link to the SM so I put it up on [dropbox](https://www.dropbox.com/sh/gomy52j7dl85abw/AADcR5JJ9EuvFD0ZpeVUYcWEa?dl=0). Check out 8.SM.11.3.1 and 8.SM.11.3.2. I'm also about to submit a paper that gives a full description of the calculations/sources in the SI, and will put that up once it's in.

Keep in mind that Branch 0.2.0 is ahead of Master, and I'll be updating from that branch.

**Comment by cardosan** [comment]
I am finding something strange in the results...but maybe it is due to my lack of understanding.
If I calculate the radiative forcing for a single pulse emission of CO2 at yr=0 I get a RF `1.75e-17` W \ m<sup>-2</sup> kg <sup>-1</sup> for year 0. What I would expect is a RF of an order of magnitude 2 times bigger i.e. `1.75e-15` W \ m<sup>-2</sup> kg <sup>-1</sup>.
Am I wrong or there is really something not correct?

**Comment by EmissionsIndex** [comment]
What is the timestep size of your emission function? For a constant emission of 1 kg over the first year the RF function expects every value in the array (in the first year) to be equal to 1. If you are trying to do a pulse emission with a timestep of 0.01 years the result will be 100x smaller than expected.

I realize this behavior is a bit weird, and welcome any ideas you have for fixing it. My work has all been with constant emissions so it hasn't mattered.

**Comment by gschivley** [comment]
Replied using the wrong account at first :)

What is the timestep size of your emission function? For a constant emission of 1 kg over the first year the RF function expects every value in the array (in the first year) to be equal to 1. If you are trying to do a pulse emission with a timestep of 0.01 years the result will be 100x smaller than expected.

I realize this behavior is a bit unintuitive, and welcome any ideas you have for fixing it. My work has all been with constant emissions so it hasn't mattered.

**Comment by cardosan** [comment]
Hey G,
it seems that this is not the issue, see [this notebook](https://gist.github.com/cardosan/85a96eb9ba407f4fb0adee4fa33724d7)
 ...but good you explained this, it is in fact a bit unintuitive :)

**Comment by gschivley** [comment]
In the first example, try setting the parameter `tstep=1`.

Here's a [notebook](https://gist.github.com/gschivley/f812cf523b3eaf32014d5d4a7108869b) with examples that each have 1.75e-15 as the RF in the first timestep.

**Comment by cardosan** [comment]
oh damn, have overlooked it :)
Sorry for taking your time and thanks ;)

**Comment by gschivley** [comment]
It's ok. Design could be improved. Maybe divide by the % of non-zero timesteps in each year? I haven't figured out if that would cause issues with other use cases. 

Could the docstring be improved? Feel free to suggest changes in an issue or create a pull request.
